name: generate snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: Platane/snk@v3
        with:
          github_user_name: priyansh-narang2308
          svg_out_path: ./assets/github-contribution-grid-snake.svg
          
      - uses: Platane/snk@v3
        id: snake-dark
        with:
          github_user_name: priyansh-narang2308
          svg_out_path: ./assets/github-contribution-grid-snake-dark.svg
          color: 'dark'
          
      - uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: ./assets
          keep_history: true
          commit_message: 'Generate Contribution Snake'
